steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['bootJar', '-Pprod', 'jibDockerBuild']
- name: 'gcr.io/cs3219-madanalogy/docker-compose'
  args: ['src/main/docker/app.yml', 'up']
- name: 'gcr.io/cloud-builders/docker'
  args: ["image", "tag", "manager", "madanalogy/manager"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "madanalogy/manager"]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-k', './']
images: ['madanalogy/manager']
