apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: madanalogy/manager
      context: ../manager
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
