apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: default
  labels:
    app: manager
spec:
  selector:
    app: manager
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
